const data = {
    products:[
        {
            _id:'1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/product-1.jpg',
            price: 240,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'La mejor zapatilla',
        },
        {
            _id:'2',
            name: 'Adidas Fit Shirt',
            category: 'Shirts',
            image: '/images/product-2.jpg',
            price: 135,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'La mejor zapatilla2',
        },
        {
            _id:'3',
            name: 'Lacoste Free Shirt',
            category: 'Shirts',
            image: '/images/product-3.jpg',
            price: 135,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 17,
            description: 'La mejor zapatilla',
        },
        {
            _id:'4',
            name: 'Nike Slim Pants',
            category: 'Pants',
            image: '/images/product-4.jpg',
            price: 78,
            brand: 'Nike',
            rating: 3.5,
            numReviews: 14,
            description: 'La mejor zapatilla',
        },
        {
            _id:'5',
            name: 'Puma Slim Pant',
            category: 'Pants',
            image: '/images/product-5.jpg',
            price: 65,
            brand: 'Nike',
            rating: 3.7,
            numReviews: 25,
            description: 'La mejor zapatilla',
        },
        {
            _id:'6',
            name: 'Adidas Fit Pant',
            category: 'Pants',
            image: '/images/product-6.jpg',
            price: 139,
            brand: 'New Atletic',
            rating: 5,
            numReviews: 240,
            description: 'La mejor zapatilla',
        },
        {
            _id:'7',
            name: 'Zapatillas Nuevas',
            category: 'Pants',
            image: '/images/product-1.jpg',
            price: 350,
            brand: 'New Atletic',
            rating: 5,
            numReviews: 240,
            description: 'La mejor azul ',
        },
        {
            _id:'9',
            name: 'Zapatillas Nuevas',
            category: 'Pants',
            image: '/images/product-1.jpg',
            price: 350,
            brand: 'New Atletic',
            rating: 5,
            numReviews: 240,
            description: 'La mejor azul ',
        },
    ],
};
export default data;